version: '3'
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./www:/var/www:cached

  php:
    build:
      context: ./phpfpm
    volumes:
      - ./www:/var/www:cached

  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306

  mailhog:
    image          : mailhog/mailhog:latest
    container_name : mailhog
    hostname       : mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
